### ISSUE TITLE
Create RemoteStringSyntax with String functions

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-flow#19]
We need an `RemoteStringSyntax` class that adds a variety of methods that work with `Remote[String]`.

Fundamentally, these methods can be implemented in terms of two primitives:

 - An operation to convert a string into a list of characters (`StringToList`)
 - An operation to convert a list of characters into a string (`ListToString`)

Given these two operations, and sufficient operations on list, together with sufficient operations on character, it should be possible to implement all other string methods.

**Comment by ashprakasan** [comment]
Please refer to - 
[*] https://github.com/zio/zio-flow/blob/main/zio-flow/shared/src/main/scala/zio/flow/RemoteBooleanSyntax.scala
[*] https://github.com/zio/zio-flow/blob/main/zio-flow/shared/src/main/scala/zio/flow/RemoteListSyntax.scala

**Comment by zalbia** [comment]
I'll take this

**Comment by zalbia** [comment]
I'm trying to implement methods such as `charAtOption` and `compare`, both of which take a single `Remote` argument, `index: Remote[Int]` and `that: Remote[String]` respectively. There are many such methods in Scala's String API, and to keep the number of members of `Remote` to a minimum, I'm writing the implementations in terms of this:

```Scala
  final case class ZipWith[A, B, C: Schema](a: Remote[A], b: Remote[B])(f: (A, B) => C) extends Remote[C] {
    override def evalWithSchema: Either[Remote[C], SchemaAndValue[C]] =
      binaryEvalWithSchema(a, b)(f, ZipWith(_, _)(f), Schema[C])
  }
```

Is this acceptable? Am I missing something?

**Comment by ashprakasan** [comment]
I don’t think this will work. Because we will not be able to serialize the function `f: (A,B) => C` in `ZipWith` 
Because we cannot serialize pure scala functions is why we introduced `Remote`
So, if we have a function represented as `Remote[(A,B)] => Remote[C]` we only need to serialise `Remote[C]` here

Lets take a simple example, 
```scala
def increment1(v : Int) : v+1
```
When represented as `Remote`, it will be 
```scala
def increment1Remote (r : Remote[Int]) : Remote.AddNumeric(r, Remote(1))
```
`Remote` does not hold a value, it is the representation of a value.

So, all we need to do is serialise is the `Remote.AddNumeric(r, Remote(1))`

**Comment by zalbia** [comment]
I came across `isBlank`: a method on `String` available since Java 11. Do we leave methods like this one out of `RemoteStringSyntax` for now or should we support them somehow?
